### PR TITLE
Module not found: Error: Cannot resolve module 'vue-style-loader'

### PR DESCRIPTION
**Pull request by zhouwenbin**

### CODE REVIEW

**Comment by egoist** [comment]
which node version r u using?

**Comment by zhouwenbin** [comment]
v5.0.0

**Comment by egoist** [comment]
it should be ok if you run it with npm 3

**Comment by zhouwenbin** [comment]
image

**Comment by zhouwenbin** [comment]
when `npm run build`

**Comment by egoist** [comment]
damn weird, what if you run`ls node_modules/vue-style-loader`

maybe the installation just broke?

**Comment by egoist** [comment]
ok, you are right 😂 extractTextPlugin wants it to be a peer dependency

**Pull request merged**
